//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministradorEventosAPI.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Evento = new HashSet<Evento>();
        }

        [JsonIgnore]
        public int ID { get; set; }

        public string Nombre { get; set; }
        public string Correo { get; set; }
        public string Contraseña { get; set; }
        public Nullable<int> RolID { get; set; }

        [JsonIgnore]
        public virtual ICollection<Evento> Evento { get; set; }
        public virtual Rol Rol { get; set; }

        [JsonProperty("RolNombre")]
        public string RolNombre { get; set; }
    }
}
